BB_CONF_FRAGMENT_SUMMARY = "Set DISTRO to proxima and add distro features"
BB_CONF_FRAGMENT_DESCRIPTION = "Proxima distribution with virtualization support"
DISTRO = "proxima"

# Add virtualization distro feature
DISTRO_FEATURES:append = " virtualization"

# Default timezone
DEFAULT_TIMEZONE = "America/New_York"

# Init manager
INIT_MANAGER = "systemd"

# Reproducible binaries
REPRODUCIBLE_BINARIES_BOOLEAN = "0"

# Build info
KBUILD_BUILD_USER = "GHI"
KBUILD_BUILD_HOST = "WARP"
